- id: '1583804847667'
  alias: New Automation
  description: ''
  trigger:
  - above: 1
    device_id: 86b73346a6fd44a79c0ab42056451a39
    domain: sensor
    entity_id: sensor.remote_knob
    platform: device
    type: value
  condition: []
  action:
  - device_id: 7b1ff9d831b24c65b5a90e91b86d301b
    domain: light
    entity_id: light.desk
    type: brightness_increase
- id: '1583805053308'
  alias: TEST
  description: ''
  trigger:
  - above: 1
    device_id: 86b73346a6fd44a79c0ab42056451a39
    domain: sensor
    entity_id: sensor.remote_knob
    platform: device
    type: value
  condition: []
  action:
  - device_id: 7b1ff9d831b24c65b5a90e91b86d301b
    domain: light
    entity_id: light.desk
    type: brightness_increase
