# bathroom
- id: bathroom_light_on
  alias: bathroom light on
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.bathroom_door
      state: 'on'
    - condition: state
      entity_id: light.bathroom
      state: 'off'
  action:
    - service: script.sun_brightness
      data:
        light_id: light.bathroom
- id: bathroom_light_off
  alias: bathroom light off
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_door
      to: 'off'
      for: 00:00:13
    - platform: state
      entity_id: binary_sensor.bathroom_door
      to: 'on'
      for: 00:30:00
  condition:
    - condition: state
      entity_id: binary_sensor.bathroom_motion
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.bathroom
- id: bathroom_light_fix
  alias: bathroom light fix
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_door
      to: 'off'
      for: 00:00:16
  condition:
    - condition: state
      entity_id: binary_sensor.bathroom_motion
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom

# bedroom_scenes
- id: bathroom_light_on
  alias: bathroom light on
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bathroom_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.bathroom_door
      state: 'on'
    - condition: state
      entity_id: light.bathroom
      state: 'off'
  action:
    - service: script.sun_brightness
      data:
        light_id: light.bathroom
- id: bathroom_light_off
  alias: bathroom light off
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_door
      to: 'off'
      for: 00:00:13
    - platform: state
      entity_id: binary_sensor.bathroom_door
      to: 'on'
      for: 00:30:00
  condition:
    - condition: state
      entity_id: binary_sensor.bathroom_motion
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.bathroom
- id: bathroom_light_fix
  alias: bathroom light fix
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_door
      to: 'off'
      for: 00:00:16
  condition:
    - condition: state
      entity_id: binary_sensor.bathroom_motion
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom

# bedroom
- id: underbed_motion_on
  alias: underbed motion on
  trigger:
    - platform: state
      entity_id: binary_sensor.underbed_motion
      to: 'on'
  condition: &night
    - condition: state
      entity_id: boolean_input.night
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.underbed
        brightness_pct: 100
        color_name: red
- id: underbed_motion_off
  alias: underbed motion off
  trigger:
    - platform: state
      entity_id: binary_sensor.underbed_motion
      to: 'off'
      for: '00:00:15'
  condition: *night
  action:
    - service: light.turn_off
      data:
        entity_id: light.underbed

# closet
- id: closet_light_on
  alias: closet light on
  trigger:
    - platform: state
      entity_id: binary_sensor.closet_door
      to: 'on'
  action:
    - service: script.sun_brightness
      data:
        light_id: light.closet
- id: closet_light_off
  alias: closet light off
  trigger:
    - platform: state
      entity_id: binary_sensor.closet_door
      to: 'off'
    - platform: state
      entity_id: light.closet
      to: 'on'
      for: 00:10:00
  action:
    - service: light.turn_off
      data:
        entity_id: light.closet

#computer
- id: computer_on
  alias: computer on
  trigger:
    - platform: state
      entity_id: person.josh
      to: "home"
  action:
    - service: light.turn_on
      data:
        entity_id: light.monitors
    - delay: '00:00:05'
    - service: switch.turn_on
      entity_id: switch.wake_computer
- id: monitors_on
  alias: monitors on
  trigger:
    - platform: state
      entity_id: switch.wake_computer
      to: "on"
  condition:
    - condition: state
      entity_id: boolean_input.night
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.monitors
- id: monitors_off
  alias: monitors off
  trigger:
    - platform: state
      entity_id: switch.wake_computer
      to: "off"
      for: "00:01:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.monitors

# frontdoor
- id: hall_lights_on
  alias: hall lights on
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
  condition:
    - condition: state
      entity_id: light.hall
      state: 'off'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall
        brightness: 20
- id: hall_lights_off
  alias: hall lights off
  trigger:
    - platform: state
      entity_id: binary_sensor.hall_motion
      to: 'off'
      for: 00:00:10
  action:
    - service: light.turn_off
      data:
        entity_id: light.hall

- id: door_open_notify
  alias: door open notify
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
      for: 00:02:00
  action:
    - service: notify.mobile_app_pixel_4
      data:
        message: 'Front door open'

# laundry
- id: laundry_light_on
  alias: laundry light on
  trigger:
    - platform: state
      entity_id: binary_sensor.laundry_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.hall_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.laundry_door
      state: 'on'
  action:
    - service: script.sun_brightness
      data:
        light_id: light.laundry
- id: laundry_light_off
  alias: laundry light off
  trigger:
    - platform: state
      entity_id: binary_sensor.laundry_door
      to: 'off'
    - platform: state
      entity_id: binary_sensor.hall_motion
      to: 'off'
      for: 00:10:00
  action:
    - service: light.turn_off
      data:
        entity_id: light.laundry

- id: laundry_leak_notify
  alias: laundry leak notify
  trigger:
    - platform: state
      entity_id: binary_sensor.laundry_water
      to: 'on'
  action:
    - service: notify.mobile_app_pixel_4
      data:
        message: 'Leak detected in laundry room'
        data:
          sticky: 'true'

# media
  alias: music on
  trigger:
    - platform: state
      entity_id: media_player.chromecast
      from: 'off'
    - platform: state
      entity_id: media_player.chromecast
      to: 'playing'
  condition:
    - condition: template
      value_template: "{{ not is_state('media_player.chromecast', 'unavailable') }}"
    - condition: state
      entity_id: group.media
      state: 'off'
  action:
    - service: switch.toggle
      data:
        entity_id: switch.music
- id: music_off
  alias: music off
  trigger:
    - platform: state
      entity_id: media_player.chromecast
      to: 'off'
      for: '00:00:10' # turns off briefly when switching
    - platform: state
      entity_id: media_player.chromecast
      to: 'idle'
      for: '00:01:00'
    - platform: state
      entity_id: media_player.chromecast
      to: 'paused'
      for: '00:05:00'
  condition:
    - condition: state
      entity_id: switch.music
      state: 'on'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.media_off

- id: ps4_on
  alias: ps4 on
  trigger:
    - platform: state
      entity_id: media_player.ps4
      from: 'standby'
      to: 'idle'
  condition:
    condition: state
    entity_id: group.media
    state: 'off'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.ps4

# night
- id: night_on
  alias: night on
  trigger:
    - platform: state
      entity_id: sensor.pixel_charger_type
      to: 'wireless'
  condition:
    - condition: state
      entity_id: person.josh
      state: 'home'
    - condition: time
      before: '05:00:00'
      after: '21:00:00'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.night
- id: night_off
  alias: night off
  trigger:
    - platform: state
      entity_id: sensor.pixel_charger_type
      from: 'wireless'
  condition:
    - condition: state
      entity_id: person.josh
      state: 'home'
    - condition: not
      conditions:
        - condition: time
          before: '05:00:00'
          after: '21:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.night

- id: read_scene
  alias: read scene
  trigger: &night_on
    - platform: state
      entity_id: input_boolean.night
      to: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.read
- id: awake_scene
  alias: awake scene
  trigger: &night_off
    - platform: state
      entity_id: input_boolean.night
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.awake

# remote
- id: living_bright_remote
  alias: living bright remote
  trigger: &b1
    - platform: state
      entity_id: binary_sensor.remote_button_1
      to: 'on'
  condition: &s_on
    - condition: state
      entity_id: binary_sensor.remote_switch
      state: 'on'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.living_bright
- id: living_orange_remote
  alias: living orange remote
  trigger: &b2
    - platform: state
      entity_id: binary_sensor.remote_button_2
      to: 'on'
  condition: *s_on
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.living_orange
- id: living_red_remote
  alias: living red remote
  trigger: &b3
    - platform: state
      entity_id: binary_sensor.remote_button_3
      to: 'on'
  condition: *s_on
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.living_red
- id: living_blue_remote
  alias: living blue remote
  trigger: &b4
    - platform: state
      entity_id: binary_sensor.remote_button_4
      to: 'on'
  condition: *s_on
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.living_blue
- id: living_off_remote
  alias: living off remote
  trigger:
    - platform: state
      entity_id: binary_sensor.remote_button_4
      to: 'on'
      for: '00:00:02'
  condition: *s_on
  action:
    - service: light.turn_off
      data:
        entity_id: light.living

- id: remote_music
  alias: remote music
  trigger: *b1
  condition: &s_off
    - condition: state
      entity_id: binary_sensor.remote_switch
      state: 'off'
  action:
    - service: switch.toggle
      data:
        entity_id: switch.music
- id: remote_video
  alias: remote video
  trigger: *b2
  condition: *s_off
  action:
    - service: switch.toggle
      data:
        entity_id: switch.video
- id: remote_switch
  alias: remote switch
  trigger: *b3
  condition: *s_off
  action:
    - service: switch.toggle
      data:
        entity_id: switch.switch
- id: remote_ps4
  alias: remote ps4
  trigger: *b4
  condition: *s_off
  action:
    - service: switch.toggle
      data:
        entity_id: switch.ps4

# screen
- id: screen_light_off
  alias: screen light off
  trigger:
    - platform: state
      entity_id: media_player.projector
      to: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.screen

# tracker
- id: front_door_tracker_update
  alias: front door tracker update
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
  action:
    - service: device_tracker.bluetooth_tracker_update
      data:
        mac: 'BT_F0:5C:77:DB:C5:C0'

# whiskey
- id: whiskey_light_on
  alias: whiskey light on
  trigger:
    - platform: state
      entity_id: binary_sensor.whiskey_cupboard
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.whiskey
- id: whiskey_light_off
  alias: whiskey light off
  trigger:
    - platform: state
      entity_id: binary_sensor.whiskey_cupboard
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.whiskey
