# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
mobile_app:
discovery:

# Text to speech
tts:
  - platform: google_translate

http:
  server_port: 8080
  
  # uses certbot for ssl cert https://certbot.eff.org/
  #ssl_certificate: /letsencrypt/live/homeassistant.joshnhickman.com/fullchain.pem
  #ssl_key: /letsencrypt/live/homeassistant.joshnhickman.com/privkey.pem

# https://www.home-assistant.io/integrations/google_assistant/ 
#google_assistant:
#  project_id: homeassistant-d31d5
#  service_account:
#    private_key: !secret google_private_key
#    client_email: !secret google_client_email
#  report_state: true
#  exposed_domains:
#    - switch
#    - light
#    - scene

wake_on_lan:

homeassistant:
  customize: !include customize.yaml

# now configured through ui 
#spotify:
  #client_id: !secret spotify_id
  #client_secret: !secret spotify_secret

recorder:
  db_url: !secret db_url
  db_max_retries: 10
  db_retry_wait: 10
  auto_purge: true
  purge_keep_days: 365
  include:
    domains:
      - person
      - sensor
      - sun
      - media_player
      - weather
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date

frontend:
  themes:
    !include conf/themes/slate.yaml

automation: !include_dir_merge_list conf/automations
group: !include_dir_merge_named conf/groups
light: !include_dir_merge_list conf/lights
media_player: !include_dir_merge_list conf/media
scene: !include_dir_merge_list conf/scenes
script: !include_dir_named conf/scripts
sensor: !include_dir_merge_list conf/sensors
binary_sensor: !include_dir_merge_list conf/binary_sensors
switch: !include_dir_merge_list conf/switches

input_boolean:
  night:
    icon: mdi:weather-night

input_number:
  cube_face:
    min: 1
    max: 6
    initial: 1

zha:
  zigpy_config:
    network:
      channel: 24
      channels: [20, 22, 24]

