# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
mobile_app:
discovery:

# Text to speech
tts:
  - platform: google_translate

http:
  server_port: 443
  base_url: https://homeassistant.joshnhickman.com
  
  # uses certbot for ssl cert https://certbot.eff.org/
  ssl_certificate: /letsencrypt/live/homeassistant.joshnhickman.com/fullchain.pem
  ssl_key: /letsencrypt/live/homeassistant.joshnhickman.com/privkey.pem

# https://www.home-assistant.io/integrations/google_assistant/ 
google_assistant:
  project_id: homeassistant-d31d5
  service_account:
    private_key: !secret google_private_key
    client_email: !secret google_client_email
#  report_state: true
  exposed_domains:
    - switch
    - light
    - scene

wake_on_lan:

group: !include_dir_merge_list conf/groups
automation: !include_dir_merge_list conf/automations
scene: !include_dir_merge_list conf/scenes
script: !include scripts.yaml
switch: !include_dir_merge_list conf/switches
sensor: !include_dir_merge_list conf/sensors
media_player: !include_dir_merge_list conf/media
light: !include_dir_merge_list conf/lights

homeassistant:
  customize: !include customize.yaml

recorder:
  include:
    domains:
      - person
      - binary_sensor  
      - sensor
      - sun
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date

device_tracker:
  - platform: ubus
    host: 192.168.1.1
    username: root
    password: !secret openwrt_password

frontend:
  themes:
    !include conf/themes/slate.yaml

