version: '3'
services:
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    ports:
      - 3306:3306
      - 3307:3307
    volumes:
      - /home/pi/homeassistant/.db:/config
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${DB_HA_PASSWORD}"
      MYSQL_DATABASE: homeassistant
    restart: unless-stopped
  homeassistant:
    depends_on:
      - mariadb
    container_name: homeassistant
    image: homeassistant/raspberrypi4-64-homeassistant:2021.4.4
    volumes:
      - /home/pi/homeassistant:/config
      - /etc/letsencrypt:/letsencrypt
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    environment:
      - TZ=America/Los_Angeles
    restart: always
    network_mode: host
    logging:
      options:
        max-size: '200k'
        max-file: '5'
