- platform: wake_on_lan
  name: wake computer
  mac: "00-D8-61-0E-16-64"
  host: 192.168.1.2
- platform: template
  switches:
    music:
      friendly_name: music
      icon_template: 'mdi:music'
      value_template: >
        {{ is_state('media_player.receiver', 'on') and 
           is_state('media_player.projector', 'off') and 
           is_state_attr('media_player.receiver', 'source', 'CHROMECAST') }}
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.music
      turn_off: &media_off
        service: scene.turn_on
        data:
          entity_id: scene.media_off
    video:
      friendly_name: video
      icon_template: 'mdi:television'
      value_template: >
        {{ is_state('media_player.receiver', 'on') and
           is_state('media_player.projector', 'on') and
           is_state_attr('media_player.receiver', 'source', 'CHROMECAST') }}
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.video
      turn_off: *media_off
    switch:
      friendly_name: switch
      icon_template: 'mdi:nintendo-switch'
      value_template: >
        {{ is_state('media_player.receiver', 'on') and
           is_state('media_player.projector', 'on') and
           is_state_attr('media_player.receiver', 'source', 'SWITCH') }}
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.switch
      turn_off: *media_off
    ps4:
      friendly_name: ps4
      icon_template: 'mdi:playstation'
      value_template: >
        {{ is_state('media_player.receiver', 'on') and
           is_state('media_player.projector', 'on') and
           is_state_attr('media_player.receiver', 'source', 'PS4') }}
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.ps4
      turn_off: *media_off
    desktop:
      friendly_name: desktop
      icon_template: 'mdi:desktop-classic'
      value_template: >
        {{ is_state('media_player.receiver', 'on') and
           is_state('media_player.projector', 'on') and
           is_state_attr('media_player.receiver', 'source', 'COMPUTER') }}
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.desktop
      turn_off: *media_off

