- platform: wake_on_lan
  name: wake computer
  mac_address: "00-D8-61-0E-16-64"
  host: 192.168.0.101
- platform: template
  switches:
    receive_chromecast:
      friendly_name: receive chromecast
      icon_template: 'mdi:music'
      value_template: "{{ is_state_attr('remote.harmony', 'current_activity', 'chromecast audio') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony
          activity: chromecast audio
      turn_off: &harmonyoff
        service: remote.turn_on
        data:
          entity_id: remote.harmony
          activity: PowerOff
    project_chromecast:
      friendly_name: project chromecast
      icon_template: 'mdi:television'
      value_template: "{{ is_state_attr('remote.harmony', 'current_activity', 'chromecast video') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony
          activity: chromecast video
      turn_off: *harmonyoff
    project_switch:
      friendly_name: project switch
      icon_template: 'mdi:nintendo-switch'
      value_template: "{{ is_state_attr('remote.harmony', 'current_activity', 'nintendo switch') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony
          activity: nintendo switch
      turn_off: *harmonyoff
    project_ps4:
      friendly_name: project ps4
      icon_template: 'mdi:playstation'
      value_template: "{{ is_state_attr('remote.harmony', 'current_activity', 'ps4') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony
          activity: ps4
      turn_off: *harmonyoff
    project_computer:
      friendly_name: project computer
      icon_template: 'mdi:desktop-classic'
      value_template: "{{ is_state_attr('remote.harmony', 'current_activity', 'computer') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony
          activity: computer
      turn_off: *harmonyoff
