- platform: template
  sensors:
    pixel_charger_type:
      friendly_name: 'pixel charger type'
      icon_template: >
        {% if is_state_attr('sensor.pixel_battery_state', 'charger_type', 'unknown') %}
          mdi:battery-unknown
        {% elif is_state_attr('sensor.pixel_battery_state', 'charger_type', 'wireless') %}
          mdi:battery-charging-wireless
        {% else %}
          mdi:battery-charging
        {% endif %}
      value_template: "{{ state_attr('sensor.pixel_battery_state', 'charger_type') }}"

