- alias: cube face
  id: cube_face
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:05:2f:9f:df' # aqara cube
  condition: >
    {{ 'flip' == trigger.event.data.command or
       'knock' == trigger.event.data.command or
       'slide' == trigger.event.data.command }}
  action:
    - service: input_number.set_value
      data:
        entity_id: input_number.cube_face
        value: '{{ trigger.event.data.args.activated_face }}'


- alias: cube
  id: cube
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_ieee: '00:15:8d:00:05:2f:9f:df' # aqara cube
  action:
    - choose:
        - conditions:
            - "{{ 'rotate_right' == trigger.event.data.command or 'rotate_left' == trigger.event.data.command }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.alldesk
                brightness_step_pct: '{{ trigger.event.data.args.relative_degrees / 3.6 }}' # 360 degrees = 100%
        - conditions:
            - "{{ 'shake' == trigger.event.data.command  }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: light.alldesk
                color_name: "{{ ['blue', 'red', 'orange'] |random }}"
      # default:
      #   - service: light.toggle
      #     entity_id: light.alldesk

