esphome:
  name: remote
  platform: ESP8266
  board: nodemcuv2
  arduino_version: dev

wifi:
  ssid: "Archmore"
  password: !secret archmore_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.101
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed Fallback Hotspot"
    password: !secret esphome_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

sensor:
  - platform: rotary_encoder
    name: "remote_knob"
    pin_a: D1
    pin_b: D2

binary_sensor:
  - platform: gpio
    pin: D0
    name: remote_switch
  - platform: gpio
    pin: D5
    name: remote_button_1
  - platform: gpio
    pin: D6
    name: remote_button_2
  - platform: gpio
    pin: D7
    name: remote_button_3

